language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk8

sudo: false

services:
  - cassandra

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

env:
  - SCALA_ENV=travis

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage compile test coverageReport codacyCoverage
