language: scala

sudo: false

services:
  - cassandra

scala:
  - 2.10.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test
